name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "17613d92-6272-485d-a82a-570dd1538403"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "f1c3d2ffe8bc4fc3a63347f660d0f5d5"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
